// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    [Migration("20220106192930_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Body = "Aliquid explicabo non perspiciatis et.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 6,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 14,
                            Body = "Enim omnis optio vero rerum illum autem aperiam officiis.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 5,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 4,
                            Body = "Ut facere inventore omnis qui qui expedita.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 18,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 16,
                            Body = "Aut iure ex ea eos earum id sed doloribus non.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 9,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 6,
                            Body = "Eum ipsum non in aspernatur.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 2,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 13,
                            Body = "Provident magni voluptatem ea.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 1,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 21,
                            Body = "Est cum quis dicta.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 8,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 1,
                            Body = "Enim et atque tenetur iusto ullam facere est.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 17,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 20,
                            Body = "In tempora id exercitationem dolore natus.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 17,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 7,
                            Body = "Sunt aliquam quia repellat voluptatem et qui qui.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 17,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 16,
                            Body = "Atque voluptatibus quia vero doloremque sunt qui consequatur.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 10,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 3,
                            Body = "Fugit quia rerum velit aut unde et molestiae vel ratione.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 14,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 15,
                            Body = "Illo exercitationem atque.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 11,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 6,
                            Body = "Ex laboriosam quia ipsum reiciendis esse illo maxime.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 4,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 2,
                            Body = "Magni dicta magnam est qui aut.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 2,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 1,
                            Body = "Aperiam delectus aut.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 11,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 10,
                            Body = "Voluptas dicta aut id est.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 6,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 4,
                            Body = "Aut perspiciatis earum.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 20,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 20,
                            Body = "Facere et dolorem ad qui sit doloremque ea in.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 9,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 14,
                            Body = "Fuga molestiae soluta reprehenderit blanditiis ratione.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106),
                            PostId = 13,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 504, DateTimeKind.Local).AddTicks(2106)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("CommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 14,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(3235),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(3790),
                            UserId = 21
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 9,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4218),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4224),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 12,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4252),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4254),
                            UserId = 16
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 4,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4273),
                            IsLike = false,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4276),
                            UserId = 8
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 7,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4294),
                            IsLike = false,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4296),
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 9,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4312),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4315),
                            UserId = 14
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 17,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4332),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4334),
                            UserId = 14
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 19,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4351),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4354),
                            UserId = 17
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 6,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4371),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4373),
                            UserId = 6
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 11,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4390),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4392),
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 9,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4408),
                            IsLike = false,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4410),
                            UserId = 17
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 4,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4426),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4429),
                            UserId = 7
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 4,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4445),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4447),
                            UserId = 18
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 13,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4464),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4466),
                            UserId = 10
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 2,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4483),
                            IsLike = false,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4486),
                            UserId = 11
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 7,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4502),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4504),
                            UserId = 21
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 11,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4521),
                            IsLike = false,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4523),
                            UserId = 20
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 12,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4540),
                            IsLike = false,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4542),
                            UserId = 19
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 5,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4566),
                            IsLike = false,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4569),
                            UserId = 14
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 17,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4585),
                            IsLike = false,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 527, DateTimeKind.Local).AddTicks(4588),
                            UserId = 7
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(2802),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1190.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(6878)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7390),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/25.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7395)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7418),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/41.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7420)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7435),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/551.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7437)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7451),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/454.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7453)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7467),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/384.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7469)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7482),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/746.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7485)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7568),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/164.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7571)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7587),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/487.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7590)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7603),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/921.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7605)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7619),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/575.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7621)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7634),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/824.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7636)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7649),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/953.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7651)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7665),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/958.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7668)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7681),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/531.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7683)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7697),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1212.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7700)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7713),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/563.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7715)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7728),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/142.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7730)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7743),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/202.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7746)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7759),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/7.jpg",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 261, DateTimeKind.Local).AddTicks(7762)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(4618),
                            URL = "https://picsum.photos/640/480/?image=107",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5459)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5663),
                            URL = "https://picsum.photos/640/480/?image=555",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5668)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5687),
                            URL = "https://picsum.photos/640/480/?image=873",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5689)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5704),
                            URL = "https://picsum.photos/640/480/?image=602",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5706)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5720),
                            URL = "https://picsum.photos/640/480/?image=365",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5722)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5736),
                            URL = "https://picsum.photos/640/480/?image=221",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5739)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5753),
                            URL = "https://picsum.photos/640/480/?image=366",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5755)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5768),
                            URL = "https://picsum.photos/640/480/?image=455",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5770)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5784),
                            URL = "https://picsum.photos/640/480/?image=504",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5786)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5799),
                            URL = "https://picsum.photos/640/480/?image=822",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5801)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5816),
                            URL = "https://picsum.photos/640/480/?image=1075",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5818)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5832),
                            URL = "https://picsum.photos/640/480/?image=380",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5834)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5907),
                            URL = "https://picsum.photos/640/480/?image=231",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5910)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5926),
                            URL = "https://picsum.photos/640/480/?image=1066",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5928)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5942),
                            URL = "https://picsum.photos/640/480/?image=614",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5944)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5958),
                            URL = "https://picsum.photos/640/480/?image=82",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5961)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5974),
                            URL = "https://picsum.photos/640/480/?image=1078",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5977)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5990),
                            URL = "https://picsum.photos/640/480/?image=336",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(5992)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(6006),
                            URL = "https://picsum.photos/640/480/?image=38",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(6008)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(6022),
                            URL = "https://picsum.photos/640/480/?image=669",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 266, DateTimeKind.Local).AddTicks(6024)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PreviewId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 17,
                            Body = "sit",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 28,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Body = "Enim et eaque qui consequatur harum quod.\nSit aut quae aut vitae adipisci amet.\nVoluptates sit consequatur.\nMolestiae et eum voluptatibus autem aut et quidem.\nAut aspernatur assumenda enim.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 39,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 19,
                            Body = "Autem exercitationem at perferendis molestias ipsum est. Id voluptatem officiis sint totam est placeat. Nobis ea eos illo ut et reprehenderit odit suscipit ullam. Minima sed voluptatem consequuntur magnam fuga voluptas modi.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 14,
                            Body = "Aliquam consectetur et sunt. Veniam esse quia sit corporis dolore nam quasi quam. Necessitatibus et placeat soluta. Laudantium ducimus quasi qui.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 14,
                            Body = "Omnis ut odit omnis.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 4,
                            Body = "Ullam nisi illo rerum eum quaerat. Et laudantium sit quia. Suscipit laborum fugit.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 25,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 1,
                            Body = "Quae quasi qui.\nAd est repellendus adipisci totam dolorum quam dolorum architecto atque.\nEa et quia beatae consectetur quo unde.\nOdio dicta quae eius fuga asperiores omnis.\nEt doloribus ipsa ea tempora velit veritatis est laborum voluptatum.\nIusto voluptas omnis.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 32,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 16,
                            Body = "Mollitia dolorem libero et veniam et molestias nihil. Incidunt iste nesciunt velit repudiandae est sint harum aperiam consequuntur. Quia similique porro laudantium quo quibusdam.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 23,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 9,
                            Body = "Consequatur et quis.\nQuasi labore autem possimus vero quisquam dolores nesciunt autem inventore.\nQuo cupiditate sed dolore tenetur.\nQuisquam et quas doloremque aut sed et atque iure temporibus.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 20,
                            Body = "amet",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 11,
                            Body = "Quaerat minima enim expedita quo. Laboriosam voluptate in a officia animi. Perspiciatis ipsa est doloribus dolor molestiae. Aperiam totam enim totam non totam facere quia accusamus est. Natus laudantium ut optio nihil qui ut autem dolorum est.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 36,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 20,
                            Body = "Mollitia vero nesciunt ut.\nMagni aperiam cumque et temporibus consequatur et.\nDolore et neque sed fuga aperiam accusantium dolores.\nPariatur laboriosam adipisci sit doloribus corporis.\nLabore sapiente maxime libero.\nAccusamus eveniet perferendis sit modi autem non voluptas.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 8,
                            Body = "Perspiciatis ut laborum quaerat.\nQuos omnis illo eos aut qui nisi provident eos minus.\nConsequatur dolorem voluptatem magni doloribus autem possimus.\nSed ea et dolores.\nMinus itaque quidem perspiciatis omnis.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 19,
                            Body = "Magnam necessitatibus nobis.\nRerum adipisci maiores est et quibusdam dolore quisquam.\nOdio occaecati aliquam.\nNon laudantium illo deleniti.\nMinima nobis ea quasi sit.\nPossimus optio qui rerum accusantium quod aut labore nemo.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 7,
                            Body = "Officia cumque quia aut at velit voluptatem occaecati. Quia odit et id alias. Repellat voluptas vel aut amet recusandae a.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 29,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 7,
                            Body = "Minima hic cupiditate laboriosam excepturi quo.\nDistinctio in natus reprehenderit eius voluptatibus omnis ut quam.\nQuo aut eos consequatur et.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 27,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 17,
                            Body = "earum",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 14,
                            Body = "Ipsam molestias est maxime sunt facere repellendus mollitia vitae.\nLaboriosam eaque odio recusandae mollitia accusantium voluptate optio ut.\nLaudantium deserunt sed quam.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 34,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 17,
                            Body = "veniam",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 32,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 16,
                            Body = "Quod beatae impedit non aperiam. Nam corrupti labore sit ullam libero deserunt accusamus. Praesentium repudiandae dolorum dicta sunt ipsum.",
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488),
                            IsDeleted = false,
                            PreviewId = 28,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 489, DateTimeKind.Local).AddTicks(4488)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("PostId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(228),
                            IsLike = true,
                            PostId = 19,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(797),
                            UserId = 21
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1274),
                            IsLike = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1279),
                            UserId = 12
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1306),
                            IsLike = false,
                            PostId = 3,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1309),
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1328),
                            IsLike = true,
                            PostId = 15,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1330),
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1348),
                            IsLike = true,
                            PostId = 7,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1350),
                            UserId = 6
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1368),
                            IsLike = true,
                            PostId = 13,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1370),
                            UserId = 17
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1388),
                            IsLike = false,
                            PostId = 7,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1390),
                            UserId = 11
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1411),
                            IsLike = false,
                            PostId = 18,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1413),
                            UserId = 15
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1431),
                            IsLike = true,
                            PostId = 17,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1433),
                            UserId = 4
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1450),
                            IsLike = false,
                            PostId = 15,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1452),
                            UserId = 8
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1469),
                            IsLike = true,
                            PostId = 10,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1471),
                            UserId = 17
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1489),
                            IsLike = true,
                            PostId = 16,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1492),
                            UserId = 15
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1508),
                            IsLike = false,
                            PostId = 15,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1510),
                            UserId = 14
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1526),
                            IsLike = true,
                            PostId = 20,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1528),
                            UserId = 4
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1545),
                            IsLike = true,
                            PostId = 15,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1548),
                            UserId = 6
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1564),
                            IsLike = false,
                            PostId = 7,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1566),
                            UserId = 8
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1584),
                            IsLike = true,
                            PostId = 12,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1586),
                            UserId = 10
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1603),
                            IsLike = false,
                            PostId = 4,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1605),
                            UserId = 11
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1622),
                            IsLike = true,
                            PostId = 6,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1624),
                            UserId = 4
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1641),
                            IsLike = true,
                            PostId = 8,
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 523, DateTimeKind.Local).AddTicks(1643),
                            UserId = 5
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 307, DateTimeKind.Local).AddTicks(9170),
                            Email = "Colton.Ebert39@yahoo.com",
                            Password = "cDsOmgj4ds1N44BwNaLM2RjdWodDupmJSXU43YuxICw=",
                            Salt = "o5gl1CvSx7RNu/jWLjyHIWwEI/MKPlR025qGA3KLdcY=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 307, DateTimeKind.Local).AddTicks(9774),
                            UserName = "Hailee.Dooley26"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 317, DateTimeKind.Local).AddTicks(806),
                            Email = "Brandy35@gmail.com",
                            Password = "22DkLs2JpI6PDmqE30QPWF9KdyrmqtF8TjVieXWPoUM=",
                            Salt = "qaJ/UsWmsq24k13SIfz7qg1lVz8LphH1OiNTNc2RH2I=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 317, DateTimeKind.Local).AddTicks(818),
                            UserName = "Stanley.Predovic94"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 326, DateTimeKind.Local).AddTicks(239),
                            Email = "Clare84@yahoo.com",
                            Password = "sAzhv0moj8XK+77IeGTe2arAw0829QPlmMGyjl7h3bQ=",
                            Salt = "hVIaPbeTfw64UoDnXWfUSFd5Ln0lJj1iu+iBPKnDK28=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 326, DateTimeKind.Local).AddTicks(253),
                            UserName = "Justyn74"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 335, DateTimeKind.Local).AddTicks(185),
                            Email = "Billie.Keeling@yahoo.com",
                            Password = "uguy29JmfmdjAQWEBDO7nClSGFaexeVE66SCusl1UKg=",
                            Salt = "cWdY35pLbvmX5msJYgbya8tQzhgR4cJwIuumSEGp5A0=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 335, DateTimeKind.Local).AddTicks(199),
                            UserName = "Jordi99"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 343, DateTimeKind.Local).AddTicks(9516),
                            Email = "Delta7@yahoo.com",
                            Password = "EAFhDSGx62ANmqRIgFFkmTVy5px1e1/j+IivtlpXxkA=",
                            Salt = "Dhcg7J1qfFkZx6qO5AixFuanhKaNSGwuvYdxIAUV0S8=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 343, DateTimeKind.Local).AddTicks(9522),
                            UserName = "Tracey.Sipes69"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 11,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 353, DateTimeKind.Local).AddTicks(1939),
                            Email = "Kody.Sanford@yahoo.com",
                            Password = "0zmr0YL4Mky1N1rXC/aXjmIIbwxPmGoWasAqfyYSIo4=",
                            Salt = "/KmZFQ0b5s2P7avW8QAEkyrNwv2s7J3GfVqiH6hbWd0=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 353, DateTimeKind.Local).AddTicks(1969),
                            UserName = "Randal18"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 362, DateTimeKind.Local).AddTicks(1632),
                            Email = "Marlin.Kovacek@gmail.com",
                            Password = "ry11JxiHQnZyvY5oLsDJ3znaPoUE/JWQTRCssupCAz8=",
                            Salt = "QvUXE+ga1LWp7U7MMjIT99Yjp7cS/R65Mr16Uyf/hF8=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 362, DateTimeKind.Local).AddTicks(1640),
                            UserName = "Martin.Kassulke"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 371, DateTimeKind.Local).AddTicks(724),
                            Email = "Deven2@yahoo.com",
                            Password = "V6o+BFP4mGJQJYFlmV/QqlfL6z16YfqWpHYla6Bj74Y=",
                            Salt = "xJTOzFubJszlu6/LF2jm6Tdzl3xvFYnUA7hKUBZ5fJc=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 371, DateTimeKind.Local).AddTicks(730),
                            UserName = "Miguel57"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 13,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 380, DateTimeKind.Local).AddTicks(270),
                            Email = "Loraine_Kling@yahoo.com",
                            Password = "sSBKx6QQDNoIPHFXFb9VV56zaKvUPSsnBu8kR5+sz2U=",
                            Salt = "0Lfl/ezGThkKYggWLv26D2eU8C85GVopAZ1F+qSbZic=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 380, DateTimeKind.Local).AddTicks(291),
                            UserName = "Jovany_Weber45"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 389, DateTimeKind.Local).AddTicks(134),
                            Email = "Joey_Kohler35@gmail.com",
                            Password = "pOd0I8BGjcWJxJlnpbjpchEl6HEFLwrVK/i5cuQUryA=",
                            Salt = "MROupjN3X8ZNeo7VkBHCTmvnVEgT76MfnQhNrGGnvUY=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 389, DateTimeKind.Local).AddTicks(141),
                            UserName = "Darius_Williamson36"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 398, DateTimeKind.Local).AddTicks(2860),
                            Email = "Kelley56@yahoo.com",
                            Password = "esiputRvWweTL+Cj5VmRdn+PJupfHD5QvTAX009xXwc=",
                            Salt = "2q6Yo44pEEalZCaLB3I1zAgHljPbrdf9cJGUTAStUOY=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 398, DateTimeKind.Local).AddTicks(2880),
                            UserName = "Jeremie83"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 17,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 407, DateTimeKind.Local).AddTicks(2769),
                            Email = "Karson46@hotmail.com",
                            Password = "nHYdUsM97xG2fMaY5mQvsz2ToxXaX/FijWSPyQbZSHI=",
                            Salt = "lFYC+S5yDj9JZHBfY2OB6OYidwfLk1Q7fcRAkZw+z6Q=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 407, DateTimeKind.Local).AddTicks(2785),
                            UserName = "Gina91"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 5,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 416, DateTimeKind.Local).AddTicks(2067),
                            Email = "Genesis2@hotmail.com",
                            Password = "ReWcPJkCvzUjh3HlEJgqORY/NZZrwwfNDrb8TcuxrKo=",
                            Salt = "zAN+2Bbpe849RAD8Ux1JE8m0NCerXb4ChIUTMyqxT14=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 416, DateTimeKind.Local).AddTicks(2076),
                            UserName = "Karelle_Dare46"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 425, DateTimeKind.Local).AddTicks(1861),
                            Email = "Ayla_Willms85@hotmail.com",
                            Password = "X96paDWt4gG3OHqoZFtCnIzgK+4zAHiHQNPTM0XyA9Y=",
                            Salt = "g0iyBet+Je7qkQWaMwh37fgd1/x0Z1uja/qq8rf8Fng=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 425, DateTimeKind.Local).AddTicks(1869),
                            UserName = "Modesto48"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 10,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 434, DateTimeKind.Local).AddTicks(1220),
                            Email = "Sylvester53@gmail.com",
                            Password = "jQyQisUk2/hw62xEbHWivhi85R6MCGIpOcMtDurR3S4=",
                            Salt = "gUBwOpESL4Yp/TbyNvI1jEQJR4ADkumGdU7vh3tnRr8=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 434, DateTimeKind.Local).AddTicks(1236),
                            UserName = "Elissa45"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 443, DateTimeKind.Local).AddTicks(1386),
                            Email = "Allan.Frami@hotmail.com",
                            Password = "kiWXKZxqtQWBkg2AI5yscRlrHjA52JH3T4a7UDXclUw=",
                            Salt = "oSk9aBDUsqj/67iNVdA7iB4AkrmlYV1qdZanXbvE9Qw=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 443, DateTimeKind.Local).AddTicks(1401),
                            UserName = "Sim_Pouros53"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 452, DateTimeKind.Local).AddTicks(2127),
                            Email = "Miracle33@yahoo.com",
                            Password = "MQwReTBj4Ek/NYO/TrHVYPFq3OqARDCGbWYUWJeIcCw=",
                            Salt = "EfjOY5oGnAX/qsSAKUzmIrYeC7LZaa4o16w59TtixpY=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 452, DateTimeKind.Local).AddTicks(2158),
                            UserName = "Schuyler_MacGyver"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 461, DateTimeKind.Local).AddTicks(2722),
                            Email = "Ora90@yahoo.com",
                            Password = "Kjdfzrz9zJTqhr27sMsvYdeOtyOOjgc0GRgt7vgq8O8=",
                            Salt = "fRfKmMd6XKPHgyFCzFQv5BFj6ovN7MlbVEBlugbivRo=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 461, DateTimeKind.Local).AddTicks(2736),
                            UserName = "Bulah.Von87"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 470, DateTimeKind.Local).AddTicks(2374),
                            Email = "Pearlie_Emmerich@yahoo.com",
                            Password = "Q2AEusvZJxF58Y1Nmu4x4HMgSzA23kFCGfizSkl98c8=",
                            Salt = "tFCXmw0nzEOZEVktkUK8nddRWdQnKu/8upqkti0HwJE=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 470, DateTimeKind.Local).AddTicks(2384),
                            UserName = "Yvonne_Boehm79"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 7,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 479, DateTimeKind.Local).AddTicks(2076),
                            Email = "Destinee95@gmail.com",
                            Password = "J0luUdJ9gSsD57Cj37v7MP/C12tbTPgJYfLxj6z11ys=",
                            Salt = "RoOXhZVvbQVHNlxmYAqzgf/D/0T2T/ezaFWEWGySlWM=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 479, DateTimeKind.Local).AddTicks(2090),
                            UserName = "Colt_Schaefer"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 488, DateTimeKind.Local).AddTicks(3280),
                            Email = "test@gmail.com",
                            Password = "euKF1e5k2L0+r5FqMBKqdnatGeIMPac1SoFtz3IMgLY=",
                            Salt = "F7R4eUMvgwNlLbc8LUs0YQuUREr4Meo9vGH++zpTqyA=",
                            UpdatedAt = new DateTime(2022, 1, 6, 22, 29, 29, 488, DateTimeKind.Local).AddTicks(3280),
                            UserName = "testUser"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("Preview");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
