// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thread_.NET.DAL.Context;

namespace Thread_.NET.DAL.Migrations
{
    [DbContext(typeof(ThreadContext))]
    [Migration("20220112191038_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 21,
                            Body = "Expedita saepe possimus modi excepturi quia fuga.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 4,
                            Body = "Neque nulla et dolorum qui iste quia earum esse nostrum.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 20,
                            Body = "Error doloribus in.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 16,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            Body = "Officia quibusdam quibusdam est et consequuntur.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 4,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 21,
                            Body = "Quo ipsa at.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 6,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 10,
                            Body = "Illum odit numquam.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 4,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 21,
                            Body = "Nam tempora unde.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 8,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 8,
                            Body = "Qui adipisci incidunt fugit tempora quo quos voluptas ipsum.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 4,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 3,
                            Body = "Quos cumque commodi odit.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 8,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 11,
                            Body = "Numquam quas veritatis maxime rerum sit.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 12,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 5,
                            Body = "Et similique magnam optio quia enim.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 21,
                            Body = "Quisquam illum perferendis praesentium ut nulla blanditiis hic vitae.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 10,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 8,
                            Body = "Iste quia quia omnis nesciunt aliquid omnis qui.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 19,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 11,
                            Body = "Dolore aut ea animi aut blanditiis consequatur eius.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 8,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 12,
                            Body = "Eum iste nihil possimus.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 8,
                            Body = "Itaque aspernatur molestias aut voluptas.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 9,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 10,
                            Body = "Ratione delectus sint.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 11,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 11,
                            Body = "Temporibus et assumenda qui error et nisi.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 2,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 4,
                            Body = "Asperiores ad voluptatem quod et consequuntur ea illum perspiciatis.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 9,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 2,
                            Body = "Labore qui dolorem eaque sequi aperiam enim ipsa corporis.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122),
                            IsDeleted = false,
                            PostId = 17,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 800, DateTimeKind.Local).AddTicks(9122)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("CommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentId = 13,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(7989),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(8661),
                            UserId = 19
                        },
                        new
                        {
                            Id = 2,
                            CommentId = 7,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9171),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9178),
                            UserId = 21
                        },
                        new
                        {
                            Id = 3,
                            CommentId = 9,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9211),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9213),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CommentId = 11,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9235),
                            IsLike = false,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9238),
                            UserId = 7
                        },
                        new
                        {
                            Id = 5,
                            CommentId = 7,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9258),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9261),
                            UserId = 6
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 3,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9281),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9283),
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 14,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9303),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9305),
                            UserId = 13
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 15,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9325),
                            IsLike = false,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9327),
                            UserId = 14
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 6,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9346),
                            IsLike = false,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9349),
                            UserId = 12
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 1,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9389),
                            IsLike = false,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9392),
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            CommentId = 9,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9413),
                            IsLike = false,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9415),
                            UserId = 10
                        },
                        new
                        {
                            Id = 12,
                            CommentId = 14,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9434),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9436),
                            UserId = 9
                        },
                        new
                        {
                            Id = 13,
                            CommentId = 17,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9455),
                            IsLike = false,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9458),
                            UserId = 15
                        },
                        new
                        {
                            Id = 14,
                            CommentId = 10,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9477),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9480),
                            UserId = 19
                        },
                        new
                        {
                            Id = 15,
                            CommentId = 5,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9499),
                            IsLike = false,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9501),
                            UserId = 19
                        },
                        new
                        {
                            Id = 16,
                            CommentId = 19,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9522),
                            IsLike = false,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9524),
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            CommentId = 9,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9542),
                            IsLike = false,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9544),
                            UserId = 6
                        },
                        new
                        {
                            Id = 18,
                            CommentId = 9,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9562),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9565),
                            UserId = 7
                        },
                        new
                        {
                            Id = 19,
                            CommentId = 5,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9583),
                            IsLike = true,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9586),
                            UserId = 20
                        },
                        new
                        {
                            Id = 20,
                            CommentId = 9,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9604),
                            IsLike = false,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 819, DateTimeKind.Local).AddTicks(9607),
                            UserId = 9
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 541, DateTimeKind.Local).AddTicks(7174),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/838.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(5473)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(6567),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/609.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(6578)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(6640),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/963.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(6647)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(6692),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/178.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(6698)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(6884),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/685.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(6890)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(6937),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/682.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(6947)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(6993),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/888.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7002)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7048),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1025.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7057)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7102),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/809.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7108)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7153),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/35.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7160)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7205),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/394.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7215)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7259),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1179.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7264)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7310),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1088.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7317)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7363),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/281.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7370)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7414),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1172.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7424)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7469),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/334.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7475)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7508),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/698.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7512)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7547),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/30.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7555)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7608),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/678.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7617)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7664),
                            URL = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/308.jpg",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 542, DateTimeKind.Local).AddTicks(7668)
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(8311),
                            URL = "https://picsum.photos/640/480/?image=483",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9196)
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9571),
                            URL = "https://picsum.photos/640/480/?image=168",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9578)
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9611),
                            URL = "https://picsum.photos/640/480/?image=814",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9616)
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9639),
                            URL = "https://picsum.photos/640/480/?image=267",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9643)
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9665),
                            URL = "https://picsum.photos/640/480/?image=128",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9668)
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9690),
                            URL = "https://picsum.photos/640/480/?image=990",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9694)
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9717),
                            URL = "https://picsum.photos/640/480/?image=463",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9720)
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9743),
                            URL = "https://picsum.photos/640/480/?image=719",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9746)
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9855),
                            URL = "https://picsum.photos/640/480/?image=977",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9860)
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9889),
                            URL = "https://picsum.photos/640/480/?image=550",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9893)
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9916),
                            URL = "https://picsum.photos/640/480/?image=646",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9920)
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9942),
                            URL = "https://picsum.photos/640/480/?image=867",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9946)
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9968),
                            URL = "https://picsum.photos/640/480/?image=811",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9972)
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9995),
                            URL = "https://picsum.photos/640/480/?image=848",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 552, DateTimeKind.Local).AddTicks(9998)
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 553, DateTimeKind.Local).AddTicks(21),
                            URL = "https://picsum.photos/640/480/?image=472",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 553, DateTimeKind.Local).AddTicks(25)
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 553, DateTimeKind.Local).AddTicks(50),
                            URL = "https://picsum.photos/640/480/?image=1077",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 553, DateTimeKind.Local).AddTicks(53)
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 553, DateTimeKind.Local).AddTicks(77),
                            URL = "https://picsum.photos/640/480/?image=1055",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 553, DateTimeKind.Local).AddTicks(81)
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 553, DateTimeKind.Local).AddTicks(103),
                            URL = "https://picsum.photos/640/480/?image=987",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 553, DateTimeKind.Local).AddTicks(107)
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 553, DateTimeKind.Local).AddTicks(128),
                            URL = "https://picsum.photos/640/480/?image=752",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 553, DateTimeKind.Local).AddTicks(132)
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 553, DateTimeKind.Local).AddTicks(155),
                            URL = "https://picsum.photos/640/480/?image=864",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 553, DateTimeKind.Local).AddTicks(159)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PreviewId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PreviewId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 4,
                            Body = "ut",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 34,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 19,
                            Body = "Deserunt adipisci rerum provident deleniti optio quia.\nDeserunt hic cupiditate.\nAut accusamus itaque fuga ex facere tenetur vel.\nEnim eos cupiditate eveniet doloribus.\nVoluptas omnis odit sint est doloribus.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 21,
                            Body = "Veritatis minus itaque perspiciatis nihil fuga.\nExplicabo reprehenderit et amet laborum voluptatem qui minus sapiente voluptatem.\nSuscipit nihil harum quos dolore.\nEnim atque aperiam repudiandae impedit.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 18,
                            Body = "Itaque eligendi modi debitis.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 35,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 13,
                            Body = "et",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 37,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 17,
                            Body = "Repellendus cupiditate debitis accusantium.\nIn quaerat perferendis repellendus similique corrupti culpa ut itaque.\nVoluptatibus eum sit non voluptas nihil vel.\nExcepturi dicta cupiditate rem aspernatur quibusdam eum saepe.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 34,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 1,
                            Body = "optio",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 15,
                            Body = "Dicta quia voluptatem quia id exercitationem.\nVoluptates facilis est quam ut et id.\nVoluptate qui commodi earum quaerat aut nesciunt eius.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 21,
                            Body = "Et vitae earum. Illo non possimus magnam tempora culpa omnis temporibus. Natus blanditiis ratione. Et beatae ipsa odio nostrum est. Quod sit exercitationem molestiae a adipisci ducimus rerum. Iusto libero error nihil porro numquam.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 15,
                            Body = "Labore officia sequi et.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 15,
                            Body = "unde",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 21,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 4,
                            Body = "Reprehenderit ut sapiente aperiam ut eum exercitationem aperiam dolores eum. Culpa saepe saepe odio eligendi. Doloribus et ut fugit qui vitae. Omnis facere modi rerum facilis in labore. Consequatur porro quia iusto facere sit vero voluptatem.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 24,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 14,
                            Body = "omnis",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 38,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 12,
                            Body = "Vero harum porro eligendi distinctio quo itaque sit.\nAliquam deleniti id voluptate iure minus.\nOmnis est quia porro alias earum ut.\nRepudiandae temporibus ut ut.\nPorro fugit aut velit quaerat.\nVoluptas occaecati ab ratione aut ut aliquam quis molestiae.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 28,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 9,
                            Body = "Dolorem ipsam necessitatibus voluptatum explicabo. Sint in qui omnis officiis accusamus deserunt. Distinctio eos autem consectetur voluptatem animi delectus architecto et. Nostrum atque placeat similique nemo possimus consequatur sit. Aut sequi ea tempora. Voluptatem harum officiis consequatur itaque enim ad perferendis.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 33,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 16,
                            Body = "Ex dolorum sequi.\nExplicabo vel voluptatem sit est officiis.\nSunt dolorem velit at expedita.\nNihil quaerat repudiandae placeat officiis sint qui.\nEos incidunt aliquid minima voluptas ea vero.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 31,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 12,
                            Body = "qui",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 22,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 10,
                            Body = "deserunt",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 18,
                            Body = "Ad aut vero quam ea voluptatem est.\nOfficiis magnam atque odit nihil et.\nCulpa voluptates ut assumenda sint quos similique et in blanditiis.\nAb facilis libero hic corporis neque possimus.\nVoluptas accusantium quis non.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 39,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 6,
                            Body = "Molestias non nostrum harum voluptas aut aut illo.\nEarum et doloremque nihil quae praesentium delectus.\nAut ipsa repellendus et hic voluptatem aliquid eius voluptatum.\nNon reiciendis voluptatibus hic nulla dicta sint natus officiis dolorem.",
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365),
                            IsDeleted = false,
                            PreviewId = 40,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 783, DateTimeKind.Local).AddTicks(3365)
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("PostId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PostReactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(5284),
                            IsLike = false,
                            PostId = 10,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(5968),
                            UserId = 13
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6501),
                            IsLike = false,
                            PostId = 20,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6507),
                            UserId = 7
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6538),
                            IsLike = false,
                            PostId = 9,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6541),
                            UserId = 20
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6562),
                            IsLike = true,
                            PostId = 3,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6565),
                            UserId = 16
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6588),
                            IsLike = false,
                            PostId = 15,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6590),
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6610),
                            IsLike = true,
                            PostId = 12,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6612),
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6632),
                            IsLike = true,
                            PostId = 8,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6634),
                            UserId = 19
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6654),
                            IsLike = true,
                            PostId = 17,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6656),
                            UserId = 21
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6676),
                            IsLike = false,
                            PostId = 11,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6678),
                            UserId = 6
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6698),
                            IsLike = true,
                            PostId = 4,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6700),
                            UserId = 7
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6721),
                            IsLike = true,
                            PostId = 19,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6723),
                            UserId = 10
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6741),
                            IsLike = true,
                            PostId = 3,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6744),
                            UserId = 13
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6762),
                            IsLike = true,
                            PostId = 2,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6765),
                            UserId = 10
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6784),
                            IsLike = false,
                            PostId = 5,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6787),
                            UserId = 12
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6806),
                            IsLike = false,
                            PostId = 10,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6808),
                            UserId = 17
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6826),
                            IsLike = true,
                            PostId = 20,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6828),
                            UserId = 13
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6847),
                            IsLike = true,
                            PostId = 6,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6849),
                            UserId = 13
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6868),
                            IsLike = true,
                            PostId = 3,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6870),
                            UserId = 5
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6889),
                            IsLike = true,
                            PostId = 13,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6892),
                            UserId = 13
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6930),
                            IsLike = false,
                            PostId = 1,
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 813, DateTimeKind.Local).AddTicks(6933),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AvatarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 598, DateTimeKind.Local).AddTicks(9674),
                            Email = "Chet40@gmail.com",
                            Password = "fGy1sAXEjUCozuTLXdmAlYt05KTHExvPRpTDCsjZMnU=",
                            Salt = "VR29j9M7tRZHu1hIXHqTlpjFw+fPjJKi919RN5sCCTM=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 599, DateTimeKind.Local).AddTicks(305),
                            UserName = "Pansy31"
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 2,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 608, DateTimeKind.Local).AddTicks(5877),
                            Email = "Steve.Ankunding@yahoo.com",
                            Password = "uc06B2JcCg3bGR3AYxgkaLXluzuHtlGhYpz7TZ1GRqQ=",
                            Salt = "2JgW5bbuNqKeRsI0LT+0p7ubXVI6o5n7S4eIo7XolWc=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 608, DateTimeKind.Local).AddTicks(5901),
                            UserName = "Eleanore74"
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 15,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 617, DateTimeKind.Local).AddTicks(9057),
                            Email = "Mack53@hotmail.com",
                            Password = "QtEpJwPYSS8b8A/+RvuKVlACD5RZdWONaKMrSn6rfJc=",
                            Salt = "JTpvJMsj6lydyxrGeaGiTDDlwoSY8Yytcl2ClXCgOZY=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 617, DateTimeKind.Local).AddTicks(9090),
                            UserName = "Mariano.Robel"
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 4,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 626, DateTimeKind.Local).AddTicks(9077),
                            Email = "Rosamond6@hotmail.com",
                            Password = "1N+/Cj8WFYJ0ab3yLeVL3LrgR56OY+SpXUnsPLTUH/M=",
                            Salt = "AlkUMt6OWqVSaGzL+jb1/VWJjRKYYe3ono3E8rqML6k=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 626, DateTimeKind.Local).AddTicks(9089),
                            UserName = "Buford_Lang"
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 635, DateTimeKind.Local).AddTicks(9078),
                            Email = "Joey_Kreiger@gmail.com",
                            Password = "Jt/ZM1dnDl30PCFLyn+XZNEkxMd5i05dpFQUR7dnG3I=",
                            Salt = "UOy1TrF9caeMzSJWric77hSCZWhV5SvCAoUgdj8CihM=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 635, DateTimeKind.Local).AddTicks(9100),
                            UserName = "Mandy52"
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 20,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 644, DateTimeKind.Local).AddTicks(9867),
                            Email = "Nya.Conn@yahoo.com",
                            Password = "9SnOF4ljiCYbcbgFIAc1YsJFXqIXB/xnvXNm0UrAOko=",
                            Salt = "Nlb5MSAnHM/+5zTXEGbovHKS9AiWInDaye8xmx8mpcU=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 644, DateTimeKind.Local).AddTicks(9895),
                            UserName = "Israel_Rempel9"
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 6,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 654, DateTimeKind.Local).AddTicks(2606),
                            Email = "Rosetta48@gmail.com",
                            Password = "mddtLUV3Tzs1xvmHEUVxXXIqJV4Ipdzuu8v8XRgc4V8=",
                            Salt = "GS6DYS7SCqx3UkoYI0+X0GaT6bQaaZchpAko7Gfz4aw=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 654, DateTimeKind.Local).AddTicks(2634),
                            UserName = "Tierra.Lang"
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 663, DateTimeKind.Local).AddTicks(3643),
                            Email = "Ryley_Johnson@hotmail.com",
                            Password = "8m/vFN4YVe5ZU+U9SoZRZB5kW+jkFC6LTvgxcwaI68s=",
                            Salt = "mvcabPOwlLlssiM/KI3l/DQmAdlcDJ4rRzRa9ojcqPU=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 663, DateTimeKind.Local).AddTicks(3671),
                            UserName = "Brittany.Daniel97"
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 672, DateTimeKind.Local).AddTicks(4127),
                            Email = "Alexie.Hamill56@gmail.com",
                            Password = "PdiJPqgm7mCVL0YvHI/SrpR9jyPFFa3SJF4+8bc09QA=",
                            Salt = "n0EH7BecrWRBmE7A6aHnm20Tpmi2u8M5LbCfADF3sfQ=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 672, DateTimeKind.Local).AddTicks(4144),
                            UserName = "Marvin.Leuschke"
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 12,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 681, DateTimeKind.Local).AddTicks(8707),
                            Email = "Adela.Klocko68@gmail.com",
                            Password = "yAWFLk0N4bd7GkMahcR9mcaQK4w03G1W50inydIYGd0=",
                            Salt = "y8NsqjKydkiTl1hiZp/KrARjaa3rm82s0vkRkxlH3BM=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 681, DateTimeKind.Local).AddTicks(8738),
                            UserName = "Jacques57"
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 690, DateTimeKind.Local).AddTicks(9916),
                            Email = "Marcella_Hettinger97@gmail.com",
                            Password = "4QBN7LRuRKSunL+nf3Wl/MMI/aqLJu5zr2Hp4Le7SNk=",
                            Salt = "3nQY6ClDQ7uU36Gh4s7JyJO2KjWmY875aJNLpNtoFis=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 690, DateTimeKind.Local).AddTicks(9934),
                            UserName = "Kaleigh_Feil"
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 20,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 700, DateTimeKind.Local).AddTicks(3515),
                            Email = "Daryl57@gmail.com",
                            Password = "9uHtUJbwDuD3keMCJfPN+MMG+4oZSB21y4kkz37+JGs=",
                            Salt = "U9c0TnbrZQWfjTMJu72657sskL8Ct08YAtmO/WcoZbE=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 700, DateTimeKind.Local).AddTicks(3544),
                            UserName = "Karianne_Dickinson"
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 709, DateTimeKind.Local).AddTicks(3194),
                            Email = "Osborne.Leuschke@hotmail.com",
                            Password = "VzmYh2xxlrJXzcglT5ojA5yu8OerI3bv7Y8DlpBOS8M=",
                            Salt = "/O6VS7qw5rcFxTWua2JxK3Rb2iGQdPfUul7n3uhdsug=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 709, DateTimeKind.Local).AddTicks(3211),
                            UserName = "Ashlynn_Schuppe"
                        },
                        new
                        {
                            Id = 14,
                            AvatarId = 8,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 718, DateTimeKind.Local).AddTicks(3458),
                            Email = "Brain.Metz@yahoo.com",
                            Password = "fnd533Ih9BnzpWYXm/e8PK3s++tP+eAbKR0LFwK3yfM=",
                            Salt = "V+xUwbM9MkI2eMP0PrHMvXQb1XzgeoLp5pEVdHfa+gA=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 718, DateTimeKind.Local).AddTicks(3476),
                            UserName = "Sigrid.Cruickshank42"
                        },
                        new
                        {
                            Id = 15,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 728, DateTimeKind.Local).AddTicks(3804),
                            Email = "Martina13@gmail.com",
                            Password = "BiMyAhczmQkABcaxb1nCqOvI5xzwq9rpH4NOzaZB0DY=",
                            Salt = "eLlZMtterngB1g407esoGFWaw8aC6XK2qLUD7KN65ec=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 728, DateTimeKind.Local).AddTicks(3823),
                            UserName = "Aletha_Towne"
                        },
                        new
                        {
                            Id = 16,
                            AvatarId = 18,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 737, DateTimeKind.Local).AddTicks(3609),
                            Email = "Keely58@hotmail.com",
                            Password = "DA1X2D9PKIaOOgEm4wDBbV/2ljC1YqwIWR69PB7ZG8k=",
                            Salt = "sw4fQnATidxlKwZ3yJ7zfYGgvin3jJp8lI4MQ9v6YDU=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 737, DateTimeKind.Local).AddTicks(3622),
                            UserName = "Davion_Moore38"
                        },
                        new
                        {
                            Id = 17,
                            AvatarId = 14,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 746, DateTimeKind.Local).AddTicks(3570),
                            Email = "Leanne_Bailey@hotmail.com",
                            Password = "/TqtlXfZtVM8FWl7axYl8PWNTsqgIB6BgnJub/rjb1Q=",
                            Salt = "yvDbPdiTKVgH/CYekjWDvy0BjAUtNR1hWYjnhHFPPjo=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 746, DateTimeKind.Local).AddTicks(3586),
                            UserName = "Adelle.Larson"
                        },
                        new
                        {
                            Id = 18,
                            AvatarId = 3,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 755, DateTimeKind.Local).AddTicks(4310),
                            Email = "Darren.Runolfsdottir@hotmail.com",
                            Password = "Cl4G3D+9N25qfeFpbGr1ol0lJPHcx/ti2z2dvaltunk=",
                            Salt = "8SMq5F5Mc6jZaonOAApIaZPmL0MZVAvvQWWEXbkn8Cs=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 755, DateTimeKind.Local).AddTicks(4331),
                            UserName = "Alessandro_Dare36"
                        },
                        new
                        {
                            Id = 19,
                            AvatarId = 19,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 764, DateTimeKind.Local).AddTicks(3751),
                            Email = "Irving_Thompson@yahoo.com",
                            Password = "seC8ZGWbFSfC5WIOeisoGZcaKk1W98SBt8N0+T9C7qI=",
                            Salt = "lo+VahcZ1X1RYzeJU3qEnDTSBilRSrWpGw9SNYGcC3I=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 764, DateTimeKind.Local).AddTicks(3761),
                            UserName = "Ruthe.Fisher6"
                        },
                        new
                        {
                            Id = 20,
                            AvatarId = 16,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 773, DateTimeKind.Local).AddTicks(3996),
                            Email = "Otha76@hotmail.com",
                            Password = "edCVkQfRxxNwsOBJQBiVCtr9nsqEOvqOft/HWEcYs4M=",
                            Salt = "2Xpiv55lN06Z8xKyjg12KP0jo3MC2p9TSNgSuQptEnc=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 773, DateTimeKind.Local).AddTicks(4016),
                            UserName = "Mattie89"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 782, DateTimeKind.Local).AddTicks(3024),
                            Email = "test@gmail.com",
                            Password = "I8iDEHzTrasfFX9gUP8xApIMrWhA3yfJCZB44X9CAr0=",
                            Salt = "FaX3ExCQpnSFCE32l+kGQ8r8KZ3GMDOwwT/wm9rhpmU=",
                            UpdatedAt = new DateTime(2022, 1, 12, 22, 10, 37, 782, DateTimeKind.Local).AddTicks(3024),
                            UserName = "testUser"
                        });
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.CommentReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Comment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Preview")
                        .WithMany()
                        .HasForeignKey("PreviewId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("Preview");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.PostReaction", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Post", "Post")
                        .WithMany("Reactions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.User", b =>
                {
                    b.HasOne("Thread_.NET.DAL.Entities.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Comment", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Thread_.NET.DAL.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
